---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: restore-cache
  image: plugins/volume-cache
  settings:
    mount:
    - ./vendor/bundle
    - ./vendor/bin
    restore: true
  volumes:
  - name: cache
    path: /cache

- name: bundle-install
  image: ruby:2.6.1
  commands:
  - bundle install --path=vendor/bundle --binstubs=vendor/bin --clean
  environment:
    RAILS_ENV: test

- name: rubocop
  image: ruby:2.6.1
  commands:
  - bundle check --path=vendor/bundle
  - bundle exec rubocop -R -fs app spec
  environment:
    RAILS_ENV: test

- name: rspec
  image: ruby:2.6.1
  commands:
  - bundle check --path=vendor/bundle
  - bundle exec rspec
  environment:
    DATABASE_HOST: db
    DATABASE_PORT: 3306
    RAILS_ENV: test

- name: rebuild-cache
  image: plugins/volume-cache
  settings:
    mount:
    - ./vendor/bundle
    - ./vendor/bin
    rebuild: true
  volumes:
  - name: cache
    path: /cache

- name: notify-slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: webhook

services:
- name: db
  image: mysql:5.7
  environment:
    MYSQL_DATABASE: drone_example_test
    MYSQL_PASSWORD: drone_example
    MYSQL_RANDOM_ROOT_PASSWORD: true
    MYSQL_USER: drone_example_test
    TZ: Asia/Tokyo

volumes:
- name: cache
  host:
    path: /tmp/cache/drone-rails-example

...
