version: '3'

services:
  dev.drone_example_db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'drone_example_dev'
      MYSQL_USER: 'drone_example_dev'
      MYSQL_PASSWORD: 'drone_example'
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
      TZ: 'Asia/Tokyo'
    ports:
      - '3316:3306'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  test.drone_example_db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'drone_example_test'
      MYSQL_USER: 'drone_example_test'
      MYSQL_PASSWORD: 'drone_example'
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
      TZ: 'Asia/Tokyo'
    ports:
      - '3317:3306'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
